### ISSUE TITLE
No access to Lecture 03 slides

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#11]
Received a message from a student:

"I don't think we have access to Thursday's first set of slides"

-Aleksandar

**Comment by madhavsuresh** [comment]
This was fixed in d78a460e25ebf345000046c87b0405088a3a0134, the slides are available https://nucs110.com/lectures/week02-lecture02

What link are they referring to?

**Comment by akuzma-011** [comment]
Command Line, Running Python ... Slides

On Apr 3, 2022 8:47 AM, madhavsuresh ***@***.***> wrote:

This was fixed in d78a460<https://urldefense.com/v3/__https://github.com/cs110sp22/cs110sp22.github.io/commit/d78a460e25ebf345000046c87b0405088a3a0134__;!!Dq0X2DkFhyF93HkjWTBQKhk!BYhAwnM2eDzfDm4FvDjl1Rz7HoqC7vPyGSyfzAJpJwSu0e7rUMb4YzvGzbT3JO1Rt4FZ$>, the slides are available https://nucs110.com/lectures/week02-lecture02<https://urldefense.com/v3/__https://nucs110.com/lectures/week02-lecture02__;!!Dq0X2DkFhyF93HkjWTBQKhk!BYhAwnM2eDzfDm4FvDjl1Rz7HoqC7vPyGSyfzAJpJwSu0e7rUMb4YzvGzbT3JA7c3EFJ$>

What link are they referring to?

**Comment by akuzma-011** [comment]
This seems to be unresolved

On Apr 3, 2022 9:06 AM, Aleksandar Kuzmanovic ***@***.***> wrote:
Command Line, Running Python ... Slides

On Apr 3, 2022 8:47 AM, madhavsuresh ***@***.***> wrote:

This was fixed in d78a460<https://urldefense.com/v3/__https://github.com/cs110sp22/cs110sp22.github.io/commit/d78a460e25ebf345000046c87b0405088a3a0134__;!!Dq0X2DkFhyF93HkjWTBQKhk!BYhAwnM2eDzfDm4FvDjl1Rz7HoqC7vPyGSyfzAJpJwSu0e7rUMb4YzvGzbT3JO1Rt4FZ$>, the slides are available https://nucs110.com/lectures/week02-lecture02<https://urldefense.com/v3/__https://nucs110.com/lectures/week02-lecture02__;!!Dq0X2DkFhyF93HkjWTBQKhk!BYhAwnM2eDzfDm4FvDjl1Rz7HoqC7vPyGSyfzAJpJwSu0e7rUMb4YzvGzbT3JA7c3EFJ$>

What link are they referring to?
