### ISSUE TITLE
Upload live lecture video for lecture 2

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#12]
Please upload/make available the live lecture 2 (currently available on Google Drive) on the public site.

**Comment by madhavsuresh** [comment]
Is this using the live lecture video from last year?

**Comment by akuzma-011** [comment]
Yes

On Apr 5, 2022 11:18 AM, madhavsuresh ***@***.***> wrote:

Is this using the live lecture video from last year?

**Comment by akuzma-011** [comment]
It is available here: https://drive.google.com/drive/folders/117gbTMtpaXCcO0cnox5Bw35V4T3Tl7-m

**Comment by madhavsuresh** [comment]
Fixed with 18534a35fe65f1a12006295f5e97b35b6bb352dd
