### ISSUE TITLE
Homework starter files missing

### ISSUE THREAD

**Issue by madhavsuresh** [cs110sp22/cs110sp22.github.io#14]
The homework starter files are missing from the google drive. For homework2 this seems to be more important, as there are libraries. See #9

**Comment by akuzma-011** [comment]
Uploaded to Google Drive.

Please CHECK before posting.

Thanks,
-Aleksandar

**Comment by akuzma-011** [comment]
Shared all homework, projects, and tutorial assignments, i.e., source code and libraries.
Please note that the share also includes solutions.
Solutions should only be shared with PMs.
