### ISSUE TITLE
Tutorial 2 starter files not yet posted

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#15]
https://nucs110.com/assignments/tutorial02

**Comment by madhavsuresh** [comment]
hmm, looks like there's some issue with the jekyll deployment. The files are on the repo via d918a8bcd882ffe0fd7d1ac8d00488fc1859a7e4, but there's some deployment authentication issue.  will look into it.

**Comment by madhavsuresh** [comment]
fixed with redeployment
