### ISSUE TITLE
Live lecture for Lecture 6 online already?

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#18]
Why is live video for Lecture 6 online already?

We said we put it online *after* the class, not before.

Please remove it ASAP. (I removed the video from the shared Google directory, but the video is still online.)

-Aleksandar

**Comment by akuzma-011** [comment]
I removed the live video from Google drive.

**Comment by madhavsuresh** [comment]
removed with 96c524a249c605063b858030c6064c677e207e32
