### ISSUE TITLE
Remove slides for live lecture before live lecture

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#3]
Madhav,

we will post live slides only after the lectures, not before.

Hence, please remove this presentation:
https://docs.google.com/presentation/d/17MgNLbGE5VaoCAVknsIJQ--s_MK3uLr8z_yNkb1R5cY/edit#slide=id.p1

I have to make changes to this presentation. 

Also, *only* upload documents from the Google Drive I shared with you, i.e., from here:

https://drive.google.com/drive/folders/18iAR2-kJYEcMhH3t1mXPOkuroJQxbQYu

Thanks,
-A

**Comment by akuzma-011** [comment]
I just realized that you uploaded all the presentations for all lectures.

We want to upload:
pre-recorded material 1 week prior to a lecture or assignment
AND
live lecture material after the lecture.

-A

**Comment by madhavsuresh** [comment]
These links seem to be from the last iteration of the course. I will remove them from all of the slides

**Comment by madhavsuresh** [comment]
#5 supersedes
