### ISSUE TITLE
Lockdown browser on Canvas

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#4]
Quizzes (real quizzes, 1, 2, and 3) will be done remotely using lockdown browsers. On Canvas, please make the lockdown browser necessary/required for these 3 quizzes. 

Thanks,
-Aleksandar

**Comment by madhavsuresh** [comment]
I may need some help with this. I have never used the lockdown browser before. It seems like the download URL is created on a per institution basis. Is there someone in the department who would know how this licensing stuff works?

**Comment by akuzma-011** [comment]
Please ask ***@***.******@***.***> , they should be able to help.

There were no problems with the Lockdown Browser last year.

-A

**Comment by madhavsuresh** [comment]
Perfect, thanks. I will ask.
