### ISSUE TITLE
Posting policy

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#5]
Madhav,

here is an updated posting policy which I hope will simplify things:

- 1 week before a class, publish all the materials for the class (Code, Slides, and Videos) available on Google Drive.

- After the class, we post the video of the live lecture (either from this year or last year). The video will be made available on Google Drive.

Lecture 1 (Thu 3/31): Currently, *the slides are missing*. Please upload 2 slides currently available on Google Drive.

Lecture 2 (Tue 4/5): Please upload tomorrow (Tue 3/29) all the materials available on Google Drive (for lecture 3).

Lecture 3 (Thu 4/7): Please upload on Thursday 3/31 all the materials available on Google Drive (for lecture 3).

Thanks,
-A

**Comment by akuzma-011** [comment]
I published the course on Canvas, so please upload the 2 slide decks for Lecture 1 as soon as you can.

**Comment by madhavsuresh** [comment]
Got it, so this be a new policy, superseding #3 . I think this policy makes sense.

**Comment by akuzma-011** [comment]
Yes, thanks

On Mar 28, 2022 11:50 AM, madhavsuresh ***@***.***> wrote:

Got it, so this be a new policy, superseding #3<https://urldefense.com/v3/__https://github.com/cs110sp22/cs110sp22.github.io/issues/3__;!!Dq0X2DkFhyF93HkjWTBQKhk!A-9l99jYFdmB-9X3-WTZ_IGHPV4TQWKDLxhlVoWTUyRdYP0gGmpFlzu-0qpOL1d9Gq8t$> . I think this policy makes sense.

**Comment by madhavsuresh** [comment]
for the lecture two slides, do you have the titles/names for the videos. Are they the same as last year?

**Comment by akuzma-011** [comment]
Same like last year

On Mar 29, 2022 8:42 AM, madhavsuresh ***@***.***> wrote:

for the lecture two slides, do you have the titles/names for the videos. Are they the same as last year?

**Comment by madhavsuresh** [comment]
fixed with 6ab2d93fd764c5f250fb970fec550fbbb0787c97, cdbf0bbbaaad45f4eb32edc7980f094b9040cf79
