### ISSUE TITLE
Quizzes on canvas

### ISSUE THREAD

**Issue by madhavsuresh** [cs110sp22/cs110sp22.github.io#6]
Currently there are not quizzes for each lecture available on canvas. Only some of the lectures have quizzes.

**Comment by akuzma-011** [comment]
That's ok. Some have, some don't.

On Mar 29, 2022 8:57 AM, madhavsuresh ***@***.***> wrote:

Currently there are not quizzes for each lecture available on canvas. Only some of the lectures have quizzes.
