### ISSUE TITLE
Addition to policy: tutorials, homeworks, projects

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#7]
One addition to the policy, so I'm opening a new issue:

- We also want to publish assignments, i.e., tutorials, homework, and projects, 1 week ahead of time.

For example, Homework 2, which is due on Friday 4/15, should be published on Friday 4/8.

Thanks,
-Aleksandar

**Comment by madhavsuresh** [comment]
fixed with f78548fbfeca04079708c0a289224f9178b645d6

**Comment by madhavsuresh** [comment]
note the website still allows students to go to the explicit URL, the url is just not available from the schedule
