### ISSUE TITLE
Homework 1 problems

### ISSUE THREAD

**Issue by akuzma-011** [cs110sp22/cs110sp22.github.io#9]
A student just told me that there are problems here:
https://nucs110.com/assignments/hw1

i.e., some materials are not showing well, there are broken pictures and links (for main.py).

-A

**Comment by madhavsuresh** [comment]
Images fixed, the main.py file doesn't seem to be in the course files zip

**Comment by akuzma-011** [comment]
main.py should be as simple as printing "Hello World"
